### ISSUE TITLE
Replacement for Behaviour callbacks in 0.1.x

### ISSUE THREAD

**Issue by novocodev** [KittyMac/flynn#19]
In version 0.0.11 the docs showed an example of passing a Behaviour as an argument to provide a callback mechanism.

What is the equivalent callback mechanism from 0.1.0, I could not see callbacks in the latest docs or examples.

e.g. should an Actor now be passed as an argument to a behaviour so that one of the actors functions can be called to send a response?

**Comment by KittyMac** [comment]
That’s correct.  I define a protocol which the actor being sent to the behavior needs to adhere to receive the callback.  I will leave this ticket here so I know to add example to the docs, thanks!

**Comment by KittyMac** [comment]
New examples added with two different mechanisms for callbacks (one using protocols and one using closures)

https://github.com/KittyMac/flynn/tree/master/Examples/ActorCallbacks
