### ISSUE TITLE
Best practice for using Flynn in SPM module depndencies 

### ISSUE THREAD

**Issue by novocodev** [KittyMac/flynn#20]
I structure my projects using Swift Package Manager, I want to use Flynn across multiple modules with nested SPM dependencies.

Are there any best practice around where initialisation, shutdown e.t.c responsibilities should be handled.

e.g. Should the top level App act as a coordinator, or should each module manage its own resources?

**Comment by KittyMac** [comment]
In regards to "best practice around where initialisation, shutdown", are you referring to Flynn.startup() and Flynn.shutdown() specifically?

**Comment by novocodev** [comment]
Yes, that was my initial concern, but good to know if there are any other considerations.

**Comment by KittyMac** [comment]
Thanks.  Generally, I would not include calls to Flynn.startup() or Flynn.shutdown() in dependencies which use Flynn.

Flynn.startup() is generally unnecessary, as it will be called automatically when the any Actor is initialized and the Flynn runtime is not started.

Flynn.shutdown()'s main use case is at program termination, if you want to allow the Flynn runtime to reach quiescence prior to the app stopping execution.  So I'd only include this in your dependency in very specific instances. For example, let's say you funnel all logging to a logging Actor, and elsewhere in your code hits a critical error and it needs to end execution early. You might call Flynn.shutdown() at that point to ensure the logging actor has time to finish whatever messages it has left to process all logging reaches the intended output).

**Comment by novocodev** [comment]
Thanks, that makes sense.
