### ISSUE TITLE
FlynnLint integration with SPM only builds

### ISSUE THREAD

**Issue by novocodev** [KittyMac/flynn#21]
I have multiple packages that use Flynn, packages are built with SPM only (i.e. no Xcode project).

Only the top level App package has an Xcode project and build.

Is it possible to integrate FlynnLint into an SPM managed build, at the moment I run a script that calls FlynnLint against the code base.

**Comment by KittyMac** [comment]
I have not discovered an easy mechanism for having a "build script" defined in SPM.  As far as I can tell, I think the SPM folks are not keen to add such a capability for security concerns (imagine adding a dependency which then runs a malicious script when you swift build).  

If you discover how to implement this nicely in SPM, I am more than happy to add it to the repo.

**Comment by novocodev** [comment]
I'll post any updates here

Thanks

**Comment by novocodev** [comment]
A went down a few rabbit holes, but found no solution in integrate flynnLint into SPM.

In the end I just added it as a step in my CI script to make sure it has been run before running "swift build"
